Remove pricing terms.
Processing the pricing leads to an error:

  Error: Cannot create a string longer than 0x1fffffe8 characters

Since we don't need that for now, just remove it.